### ISSUE TITLE
Use zxcvbn for password strength

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup-pw/buttercup#1]
Use zxcvbn for password strength recommendations in the interface: https://www.npmjs.com/package/zxcvbn

**Comment by naitian** [comment]
Is this still an issue? I see that the ready/in progress tags have been added and removed.

**Comment by perry-mitchell** [comment]
Yes.. We were using a project mgmt tool for github and it made a bit of a mess here. This task is still valid.

**Comment by sallar** [comment]
Closed by #92
