### ISSUE TITLE
Improve trash usability

### ISSUE THREAD

**Issue by alireza-ahmadi** [buttercup-pw/buttercup#100]
I think Trash group needs a couple of changes:

- Prevent users from creating a new entry in Trash group
- Allow users to empty Trash group(Maybe using a right click menu following by a confirmation dialog)

If you agree, I can send a pull request for these features in the next few days.

**Comment by sallar** [comment]
@alireza-ahmadi Thanks! These are valid concerns. And the PR is certainly most welcome.

**Comment by alireza-ahmadi** [comment]
Great 👍, I will start working on it as soon as possible.

**Comment by perry-mitchell** [comment]
Please be aware that this should be implemented in parallel in the core. It's not enough that the interface protects against it, it should be blocked at the functionality level.

**Comment by perry-mitchell** [comment]
This shouldn't be closed until it's also implemented in the core.

**Comment by alireza-ahmadi** [comment]
@perry-mitchell Thanks for the notice.

**Comment by perry-mitchell** [comment]
I could also implement it, was just mentioning that they should go together 🙂

**Comment by alireza-ahmadi** [comment]
@perry-mitchell If you are okay I prefer to implement core functionality as well. I like to read most of the application source code and implementing this feature can be a good excuse for that. I will let you know if there was any problem in the implementation process.

**Comment by sallar** [comment]
@alireza-ahmadi Are you still doing this?

**Comment by perry-mitchell** [comment]
This is already in progress in the core (I started it recently), so perhaps this should be blocked until that part is done (buttercup-pw/buttercup-core#121)

**Comment by sallar** [comment]
Another friend was also interested in doing this (the UI part). Thats why Im asking

**Comment by perry-mitchell** [comment]
The core part (buttercup-pw/buttercup-core#121) is now complete and in production as [v0.31.0](https://github.com/buttercup-pw/buttercup-core/blob/master/CHANGELOG.md#v0310).

**Comment by perry-mitchell** [comment]
So i've released buttercup-pw/buttercup-core#131 (Trash emptying) as 0.32.0: https://github.com/buttercup-pw/buttercup-core/blob/master/CHANGELOG.md#v0320

This is not yet in the core-web package so it can't be used here just yet, but this UI functionality can be added without waiting.

**Comment by sallar** [comment]
@perry-mitchell thanks! 
@alireza-ahmadi I gave this a go, since you haven't updated the status, so Im assuming I can do this. It'll be merged soon. Thanks!
