### ISSUE TITLE
Pressing enter in entry form does not apply UI changes

### ISSUE THREAD

**Issue by alireza-ahmadi** [buttercup-pw/buttercup#101]
When you try to create a new entry, if you press the **Save** button everything works fine, but when you press the **Enter (return)** key, the entry saves but the application does not exit edit mode and the entry does not appear on the entries list so the user thinks that the password entry is not created at all. In this situation, you can see the created entry by switching to another group and switching back to your entry's group. Also, when you press the **Enter (return)** key, the **Save** button stops working.

![aban-30-1395 22-51-38](https://cloud.githubusercontent.com/assets/1054228/20465537/726fbd04-af74-11e6-9ed3-0cf6b953e5b4.gif)

**Comment by sallar** [comment]
😱 thanks for letting us know. will take a look at this asap.
