### ISSUE TITLE
Allow users to open `.bcup` file by drag and drop

### ISSUE THREAD

**Issue by alireza-ahmadi** [buttercup-pw/buttercup#103]
Currently, dragging a `.bcup` file into the application window causes an awkward situation which forces the user to re-run application. I think users should be able to open `.bcup` file using drag and drop. If for any reason implementing drag and drop is not possible, they should receive a message instead of seeing the file contents.

![aban-30-1395 23-35-55](https://cloud.githubusercontent.com/assets/1054228/20465743/294d07c0-af7a-11e6-8a42-b0efdce6313f.gif)

**Comment by perry-mitchell** [comment]
Thanks @alireza-ahmadi - Definitely a good feature to have.

**Comment by sallar** [comment]
Thanks @alireza-ahmadi, that can be very handy. it's possible to achieve this by listening to "will-navigate" event on `focusedWindow` in the main process. Will look into this at the same time I'm going to look into #33
