### ISSUE TITLE
Application does not run after closing the window

### ISSUE THREAD

**Issue by alireza-ahmadi** [buttercup-pw/buttercup#104]
When you close the application using the traffic lights buttons(that three red, yellow, and green buttons in the top-left corner of windows), the application window closes but the application does not quit and **Buttercup icon** stays in the dock. Normally, users should be able to re-open the application window again by clicking the **Buttercup icon** in the dock but currently, clicking application's icon does nothing and users are forced to quit and re-run the application for using it.

This issue can get fixed either by quitting the application completely when the user closes all application windows or by re-opening application window when the user clicks the dock icon.

**Comment by perry-mitchell** [comment]
Hmm.. I feel either option could work. Either clean quit (my preference) or spawn window when re-clicked. Maybe to just save on resources we should full-quit.. I don't see a use-case in leaving it running for nothing.

What do you think @sallar ?

**Comment by sallar** [comment]
@perry-mitchell @alireza-ahmadi It's currently possible to re-open the window by pressing CMD/Ctrl+N or "Archive/File>Open new window" menu item. But opening a new window by clicking on the dock icon can be another option. We can add that one too.

**Comment by alireza-ahmadi** [comment]
@sallar Oh! Sorry, I didn't notice those menu items. However, I think implementing any of mentioned scenarios would improve user experience because those are the default behavior of most of other applications.

**Comment by perry-mitchell** [comment]
This bricks the application.. so I've raised the priority. In my opinion the app shouldn't close, but the main window should be re-opened when clicking the icon in this state:

![image](https://cloud.githubusercontent.com/assets/3869469/21484608/886a723e-cb9e-11e6-9526-fc16432d26e6.png)

**Comment by sallar** [comment]
@perry-mitchell I will fix this tonight
