### ISSUE TITLE
Remove folder arrow if no sub-folders exist

### ISSUE THREAD

**Issue by naitian** [buttercup-pw/buttercup#118]
![image](https://cloud.githubusercontent.com/assets/3933321/21597004/62c36a7c-d111-11e6-806a-0d26c70c5c17.png)

![image](https://cloud.githubusercontent.com/assets/3933321/21597006/69944aa6-d111-11e6-92a2-3e7160a9bf35.png)

The folder looks like it can be expanded to reveal subfolders, but no subfolders are present.

**Comment by sallar** [comment]
@naitian this is fixed and will go out in next release. thanks!
