### ISSUE TITLE
Copy password feature overrides global copy

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup-pw/buttercup#132]
When trying to copy a meta title, the entry password is copied instead.

![image](https://cloud.githubusercontent.com/assets/3869469/21752017/9b037856-d5d9-11e6-8730-08e25e17abf1.png)

**Comment by sallar** [comment]
Actually the copy feature has lost it's default behaviour because right now
cmd+c "always" copies the entry password. No matter where you press it.
It's global.

-- 
*Sallar Kaboli*
Senior Software Engineer
+358 40 5827545 <+358%2040%205827545>
