### ISSUE TITLE
View password without editing

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup-pw/buttercup#133]
It would be great to be able to show the password without editing:

![image](https://cloud.githubusercontent.com/assets/3869469/21752029/c872148c-d5d9-11e6-9045-ae320a29ceca.png)

Copying the password is not always what's needed, and viewing it could help. Perhaps a view button beside the copy? The ability to hide the password should also be considered. Perhaps it could also hide on unfocus.

**Comment by sallar** [comment]
It's possible. Right click and select reveal password.

**Comment by perry-mitchell** [comment]
@sallar Ah, but that's a bit tricky when you don't know that. The hover only shows "Copy", so it's not immediately clear that there are any other features..

**Comment by perry-mitchell** [comment]
I think from usability that we should discuss how we could improve all interaction around the password field..

**Comment by sallar** [comment]
That can be solved by a "split" button. A button that has an arrow beside it and opens the submenu that has reveal... or just add the reveal right there but it will be ugly. But this should be "UI" enhancement type of thing only.

**Comment by perry-mitchell** [comment]
I would say that having a reveal button is almost more important that copy, having thought about it. We could poll it. The copy password would almost be more intuitive on right click, and the reveal being the button:

![image](https://cloud.githubusercontent.com/assets/3869469/21752207/02171f04-d5dd-11e6-8a85-8ac28d738d9f.png)

**Comment by sallar** [comment]
But would you find yourself looking at a 20 chars long password or copying it more? I still think copy is more important, but that's just me. We can poll it too.

**Comment by perry-mitchell** [comment]
I think we should poll it at very least, because I find myself copying it char by char onto my device sometimes (if I don't want to install a password manager there). That's more important than copying which I would normally do by right-clicking.

**Comment by perry-mitchell** [comment]
I think the poll will show that 2 buttons is preferred.. which I quite like the idea of. It could simply be two permanent buttons visible in some neat way at the end of the input:

![image](https://cloud.githubusercontent.com/assets/3869469/21758384/deb89490-d643-11e6-92ef-b1388e69a2bb.png)

What do you think @sallar ?
