### ISSUE TITLE
Fuzzy search usability

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup-pw/buttercup#135]
Perhaps the current searching system isn't exactly what users might expect. For instance, a few random characters still shows results:

![image](https://cloud.githubusercontent.com/assets/3869469/21752076/e31ba68a-d5da-11e6-97ea-572c3c1fc4ad.png)

Depends on buttercup-pw/buttercup-core#135

**Comment by sallar** [comment]
We use [Fuse.js](https://github.com/krisk/Fuse) for searching. It has some options and can be configured. Right now it's default config and supports "fuzzy" searching which is what produces the result in the screenshot (it guesses the result from all chars in title and username). But I don't think this is a problem.

**Comment by perry-mitchell** [comment]
> it guesses the result from all chars in title and username

But should it show results that have no relation to the string entered in the search box? Seems a bit misleading. We could even do a case-insensitive _contains_ search, and just let Buttercup manage it...

**Comment by sallar** [comment]
I think it's pros are worth the cons. Implementing a search function by yourself might not cover all bases. for example in your screenshot "plystaton" will still match the first item, which is very useful IMO.

**Comment by perry-mitchell** [comment]
Yes, true.. but should a random group of characters match all results? Probably not. 

And it might be worth considering whether or not this plugin will allow us to deep-search the archive.

**Comment by sallar** [comment]
I still can't see why this is a problem. Unless there is a better way to handle the search and not lose any functionality it already has, this is the best I could come up with.

**Comment by perry-mitchell** [comment]
Closed in favour of #136
