### ISSUE TITLE
Page titles are visible in windows & ubuntu

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup-pw/buttercup#137]
The page titles used for programmatic location detection are visible in the titlebars on linux and windows:

![image](https://cloud.githubusercontent.com/assets/3869469/21758057/4ef375b2-d640-11e6-94ae-d7f3240eee9f.png)

![image](https://cloud.githubusercontent.com/assets/3869469/21758317/1a2bd272-d643-11e6-86fc-6af272d8d041.png)

**Comment by perry-mitchell** [comment]
So these areas use the title for navigation detection:

- https://github.com/buttercup-pw/buttercup/blob/2f1f3c697418a3359dfed2a92f8930bd618652fe/app/index.html#L5
- https://github.com/buttercup-pw/buttercup/blob/9ccc1261b6e7da90c7bbd5e7626c50afec0e7966/src/main/config/menu/file.js#L32
- https://github.com/buttercup-pw/buttercup/blob/2f1f3c697418a3359dfed2a92f8930bd618652fe/src/renderer/redux/modules/workspace.js#L27

Perhaps something like `browserWindow.webContents.getURL()` could be used with some regex to detect if it's the intro or logged-in area?

**Comment by sallar** [comment]
@perry-mitchell Thanks for the suggestions mate. The problem here is right now we don't "navigate". I changed the title detection method to be something nicer, and also fixed the titles for Windows and Linux to something that has meaning.
