### ISSUE TITLE
Confirm password when creating new archive

### ISSUE THREAD

**Issue by Jonas-Drotleff** [buttercup-pw/buttercup#158]
When creating a new archive and giving it a master password, the user should be asked to confirm the password (simply two textfields) as user tent to choose a complicated and long password as a master password and spellings are very likely. Or at least make it possible to print out the password clear (letters instead of *)

**Comment by sallar** [comment]
Thanks, but this is a duplicate of #35, #62 and #78. This is prioritized and will be done soon :)

**Comment by Jonas-Drotleff** [comment]
Oups, sorry 😬

**Comment by sallar** [comment]
@Jonas-Drotleff No problem at all :)
