### ISSUE TITLE
Feature request: arrange entries

### ISSUE THREAD

**Issue by jarl-tornroos** [buttercup-pw/buttercup#176]
It would be great to have the possibility to arrange entries for example by name. Now they are in the order they got entered.

**Comment by sallar** [comment]
It will help to have a "sort by" button next to the search field. what do you think @jarl-tornroos @perry-mitchell

**Comment by perry-mitchell** [comment]
If it's a permanent option that has its last value remembered between closes of the application, that would be perfect.

You could sort:
 - alphabetically 
 - last access?

But if we start with alphabetical sorting my default that would already be better imo.

**Comment by sallar** [comment]
@perry-mitchell we can make the default alphabetical, but also give options: "a-z, z-a, last access"?

**Comment by perry-mitchell** [comment]
Sure. I like that. I guess I mean that we could straight away sort it alphabetically without the need for a button until we make updates later?


Also, last access will need more implementation..

**Comment by sallar** [comment]
Of course, I will make the a-z the default. Also by last access I actually meant the default lol. but yeah a real last access would be nice in the future.

**Comment by perry-mitchell** [comment]
> I actually meant the default
Sorry, I'm thick. What do you mean by default?

> real last access would be nice in the future
Absolutely. Having the a-z sorting now would just improve the locating of folders so much.. very low-hanging fruit.
