### ISSUE TITLE
ChromeExtension local filesystem

### ISSUE THREAD

**Issue by xtrasmal** [buttercup-pw/buttercup#196]
hi there, 

I was looking for information on how to add a local archive. Maybe through html5 filesystem api?
Right now there are only 3 visible; Dropbox, Owncloud en Webdav. All of them ask me to log in somewhere(super lame). The additional login info will be stored somewhere(i assume), which feels insecure.

**Comment by sallar** [comment]
@xtrasmal The additional login info are stored right in your browser and never leave it.

Right now only the desktop app has local filesystem capabilities. But we are working to add cloud to desktop app and also filesystem to the chrome extension. 

Thanks.

**Comment by xtrasmal** [comment]
@sallar 
I have a solution for me. I created a local Virtual Host. Connected to my local WebDav server. 
So now I do not need to move out of my LAN.

**Comment by perry-mitchell** [comment]
@xtrasmal I don't think it's a completely bad idea using the local filesystem if the HTML5 API is straightforward enough, I've just never looked at it. Thanks for bring this up - we'll definitely look into it as an option despite your situation having been solved for now.

**Comment by sallar** [comment]
@perry-mitchell maybe recreate this issue in the browser-extension repo?
