### ISSUE TITLE
Update notifications

### ISSUE THREAD

**Issue by sallar** [buttercup-pw/buttercup#22]
Once we’ve shipped, we’ve shipped. We can’t ask people to always re-download our stuff. Let’s add an auto-update functionality according to [this guide](https://github.com/atom/electron/blob/master/docs/api/auto-updater.md).

**Comment by perry-mitchell** [comment]
The auto updater looks shakey, so I suggest the following:

Store a JSON file on the server with the current version and the URL to the installer. The file could look like this:

```
{
    "version0": {
        "version": "0.2.3",
        "title": "Buttercup alpha 0.2.3",
        "importance": "normal",
        "installer": "http://download.com/buttercup-0.2.3.exe"
    }
}
```

**Comment by perry-mitchell** [comment]
URL: http://buttercup.pw/update.json

Importances: "normal", "important", "critical"
