### ISSUE TITLE
Choosing "quit" from system menu results in error

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup-pw/buttercup#29]
A system error occurs when selecting "Quit" from the Buttercup system menu on Mac.

**Comment by kbariotis** [comment]
Hello @perry-mitchell, great project you've putted there. :)

I played a bit with this issue. It seems like having an Archive window open and the Quit command is clicked, the Archive window will receive the [`Closed`](https://github.com/buttercup-pw/buttercup/blob/master/source/app/events.js#L49) event which will attempt to open an Intro window and this will mess up the quit process.

I tried to separate the CMD+Q command from when the user close windows. The `window-all-closed` will handle the situation when the user close windows so the CMD+Q command won't try to reopen windows.

This will work with the current window strategy. Intro window is open but no Archive windows. When the Intro closes, the app quits. Archive window is open but no Intro window. When the Archive closes, the Intro will reopen.

This also got me into thinking that the app must be able to prevent from quitting e.g. when the use is in the middle of adding an entry. But I believe that could go in a separate task.
