### ISSUE TITLE
Register file type association (.bcup) OSX

### ISSUE THREAD

**Issue by euwars** [buttercup-pw/buttercup#33]
Register .bcup type so files can be opened via Double click / Open with.

**Comment by perry-mitchell** [comment]
Suggestions for implementation here are welcome - I have no experience doing this programmatically.

Perhaps [**duti**](http://duti.org/documentation.html) could work?

**Comment by ph1p** [comment]
Maybe these two links will help a little bit:
- https://www.theodo.fr/blog/2015/12/link-files-to-application-in-windows/
- https://discuss.atom.io/t/double-click-to-open-files-into-electron-app/21713/6

**Comment by sallar** [comment]
@ph1p thanks, I have figured out the extension association (`electron-builder` package does it), my problem is now I don't know how to test it. I don't know how does the OS pass the file path to the app.

**Comment by ph1p** [comment]
Mac: all information about the app and its file extensions are stored in a file called **Info.plist** (XML-file). Its located in your app. Here is the **Info.plist** of buttercup:
<img width="795" alt="info_plist" src="https://cloud.githubusercontent.com/assets/15351728/20184094/c769d098-a767-11e6-807b-47ac13c80d06.png">
I don't know how windows or linux handle it and i've no idea how to test it.

I think when the OS knows the connection between file and app (Info.plist, registry ...), it opens the app and calls a native method. Electron then triggers one of these events https://github.com/electron/electron/blob/master/docs/api/app.md

I'm just brainstorming cause I like your project and want to help you! :)

**Comment by sallar** [comment]
thanks @ph1p, those events are really helpful. Will try to make it work ASAP.
