### ISSUE TITLE
Cmd + A for editing titles and group names

### ISSUE THREAD

**Issue by BehrouzIX** [buttercup-pw/buttercup#34]
Cmd + A doesn't work if you want to edit the titles or group names.

**Comment by sallar** [comment]
Cmd+A works everywhere as far as I tried. Please re-open if proven otherwise.

**Comment by naitian** [comment]
Cmd+A seems to work when running using electron from the command line (i.e. `electron .`), but doesn't work (for me, also) when running the alpha release downloaded and installed from the packages page... I'm not sure what's up with that.

**Comment by perry-mitchell** [comment]
I can confirm this @naitian - The installed version doesn't respond to Cmd+A, whereas the development version does.

**Comment by sallar** [comment]
I just double checked the issue:
The installed version didn’t support CMD+A because the app was lacking system menus. As a result of issue #45 being resolved, the `Edit` menu is in place now and CMD+A works as expected.
We’ll leave this issue open until the next version has been released.

**Comment by sallar** [comment]
Closed by #92
