### ISSUE TITLE
No confirmation for deleting a document

### ISSUE THREAD

**Issue by emehran** [buttercup-pw/buttercup#41]
Hi there. 
The UI of ButterCup is amazing. However, it would be nice to as for confirmation before deleting a password document. As it is saved automatically on Mac, when a user delete a document accidentally, theres no way to get it back.

**Comment by perry-mitchell** [comment]
Good point! This is definitely something we should include.

**Comment by emehran** [comment]
Great, I'm not sure if there is a backup folder for removed ones. Like what we see in KeepassX. When you remove a document, it will goes to trash folder for backup purposes.

Thank you!

**Comment by perry-mitchell** [comment]
@emehran That's a good idea - Perhaps we should update this to be for a trash folder - what do you think?

**Comment by emehran** [comment]
if you ask me, I think both are necessary. A confirmation message for removing a sensitive data seems ok, also temporary trash (can be named backup) for backup backup.
