### ISSUE TITLE
Setup instructions don't seem to work

### ISSUE THREAD

**Issue by lietu** [buttercup-pw/buttercup#42]
```
npm install -g electron-prebuilt jspm
npm install
grunt build
electron .
```

Results in an error:
![image](https://cloud.githubusercontent.com/assets/1296558/12697309/d55a016a-c788-11e5-9f7f-b8b27b46477f.png)

Windows 10, Node v0.12.7

**Comment by perry-mitchell** [comment]
Ah.. Yes - The core uses a symlink to create a consistent pathing regime throughout the system - It's the only way to avoid global definitions of "root paths" and crazy breadcrumb directories like "../../../../file.js".

Seems as though windows still doesn't like the symlink ("__buttercup") - that'll be why it's failing.

**Comment by perry-mitchell** [comment]
Related to the core: buttercup-pw/buttercup-core#32
