### ISSUE TITLE
New database should have slightly better defaults

### ISSUE THREAD

**Issue by lietu** [buttercup-pw/buttercup#48]
E.g. something like this could be a nice screen to see after creating the new database:

![image](https://cloud.githubusercontent.com/assets/1296558/12704930/9aeb5998-c86e-11e5-809d-d5f5ccbf05a8.png)

.. that way users don't have to loop for the new group button, then name it something, then click on it and find the new document -button. Most likely the first action they want to do when creating a new database is to add a new document to it.

**Comment by perry-mitchell** [comment]
Good point.. What do you think @sallar ?

**Comment by sallar** [comment]
I agree. We should think about that for Beta.

**Comment by perry-mitchell** [comment]
This has been partially implemented with the addition of General and Trash (0.13.0 of core). Adding a sample entry in the general group should finish this off, but that may be a task for this repo rather than the core.
