### ISSUE TITLE
Publish to Brew/Caskroom

### ISSUE THREAD

**Issue by marksteve** [buttercup-pw/buttercup#53]
Would be install if I could `brew install` this baby

**Comment by sallar** [comment]
Thanks for the suggestion. By installing it using `brew` you mean `brew cask` right? Because to my knowledge `brew cask` is what people use for installing and uninstalling app binaries and `brew install` itself is usually for bash executables.
http://caskroom.io/

**Comment by marksteve** [comment]
Yep. I meant cask. :D

**Comment by sallar** [comment]
Thanks. I will look into this further as soon as I got more time. Here’s a guide for submitting new apps to brew cask for our future reference:
https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by marksteve** [comment]
Will try to help out if I get free time as well. Thanks!

**Comment by perry-mitchell** [comment]
Following up, you're right @sallar - specifically Cask is for GUI applications:

> Homebrew Cask extends Homebrew and brings its elegance, simplicity, and speed to OS X applications and large binaries alike.

Would be amazing to get our next version published there!

**Comment by sallar** [comment]
@perry-mitchell I agree, we should do it soon :)

**Comment by perry-mitchell** [comment]
Deprioritised.. Not the most important item right now.

**Comment by sallar** [comment]
After the [This PR](https://github.com/caskroom/homebrew-cask/pull/28724) has been merged into master, Buttercup will be available to install using: `brew cask install buttercup`. @marksteve Thanks for reporting and sorry it took longer than expected! Like a year... 😕
