### ISSUE TITLE
Entries searching

### ISSUE THREAD

**Issue by mpourismaiel** [buttercup-pw/buttercup#60]
I have two entries 'Buttercup' and 'Some other website with a cup' and searching 'cup' hides both of them. Also searching any other phrase does the same thing.

**Comment by perry-mitchell** [comment]
Thanks @mpourismaiel - That seems to be the case, we'll need to fix the search.

Thinking it might be wise to have it search the entire archive rather than just the current group.

**Comment by sallar** [comment]
Closed by #92
