### ISSUE TITLE
Can't open app after grunt install

### ISSUE THREAD

**Issue by mpourismaiel** [buttercup-pw/buttercup#61]
I tried to fork and work on buttercup but I get this error after running `grunt build; electron .`.

![Error message](http://i.imgur.com/WIlUN9N.png)

It's worth mentioning I had no problem installing Buttercup using the `.deb` package.

- node v5.2.0
- npm v3.3.12
- electron v0.36.7

**Comment by naitian** [comment]
Make sure you are in the buttercup directory.

**Comment by perry-mitchell** [comment]
Perhaps you could also share your node/npm/electron versions.

**Comment by mpourismaiel** [comment]
- node v5.2.0
- npm v3.3.12
- electron v0.36.7

**Comment by perry-mitchell** [comment]
After checking a few other linux posts, most people seem to stop the GTK messages by installing the missing modules: `sudo apt-get install libcanberra-gtk-module`. Obviously this is strange to have come up at all.

What distro are you on? Are you able to run any other electron apps? (eg. https://github.com/hokein/electron-sample-apps)

**Comment by mpourismaiel** [comment]
I can run other electron app with no problem, with those GTK error messages coming up!
I'm running Elementary OS (based on Ubuntu 14.04).

Although this doesn't seem to be a problem with the environment. The error message says:
> Error: Cannot find module '__buttercup/classes/Archive.js'

**Comment by perry-mitchell** [comment]
Hmm. That error will be in the buttercup-core project - `__buttercup` is actually a symlink that makes managing pathing much easier.

Could you try going into the node_modules dir, into "buttercup", removing its node_modules directory and running `npm install` in there? Inside its node_modules, the symlink "__buttercup" should point upwards to its own source folder.

**Comment by mpourismaiel** [comment]
That did it. I wonder why it didn't create the symlink before. Anyways, thanks a lot!

**Comment by perry-mitchell** [comment]
Yes it's quite strange. It's part of the `npm install` command, so something may have caused it not to run.

Please re-open if it occurs for you again. Cheers.
