### ISSUE TITLE
Buttercup dist won’t open

### ISSUE THREAD

**Issue by sallar** [buttercup-pw/buttercup#65]
After building Buttercup Mac version using `grunt dist`, the app throws an error and won’t open:

![image](https://cloud.githubusercontent.com/assets/768052/12870027/09ea0446-cd3a-11e5-9141-db66946e7c6d.png)

**Comment by sallar** [comment]
Turns out that to fix this, `node_modules` needs to be removed and `npm install` again.

**Comment by perry-mitchell** [comment]
Seems something was up with the current state of installation.. Hopefully this doesn't crop up again.
