### ISSUE TITLE
Saving and loading operations are slow

### ISSUE THREAD

**Issue by sallar** [buttercup-pw/buttercup#75]
As a result of the increasing pbkdf2 iterations (https://github.com/buttercup-pw/buttercup-core/pull/46) the UI has gotten slow, since all operations are sync in the app. 
The best way to fix this would be make backbone model operations async so the UI doesn’t wait for backend ops to complete before updating elements.

**Comment by perry-mitchell** [comment]
Is this still valid @sallar?

The save time due to high iterations is somewhat necessary - it provides a good layer of security. I imagine the time will grow longer when we up the default iteration counts on the core.

**Comment by sallar** [comment]
@perry-mitchell this will be closed by #92

**Comment by sallar** [comment]
Closed by #92
