### ISSUE TITLE
Selecting a password displays the "save" option

### ISSUE THREAD

**Issue by Jameskmonger** [buttercup-pw/buttercup#82]
1. Open a document you've already created
2. Click the binoculars to show the password
3. Click the password and click CTRL+A
4. The save option appears at the bottom even though there have been no changes

**Comment by perry-mitchell** [comment]
This may be auto resolved by @sallar's refactor.

**Comment by sallar** [comment]
@perry-mitchell Updated the PR to include this

**Comment by sallar** [comment]
Closed by #92
