### ISSUE TITLE
buttercup.pw is serving an invalid certificate

### ISSUE THREAD

**Issue by jon-walton** [buttercup-pw/buttercup#83]
The website (https://buttercup.pw) is currently serving an expired certificate,

Serial: ‎01 02 45 1e a9 15 94 7d 69 42 f5 2e dc 64 b1 2d 95 90
ValidTo: ‎Monday, ‎9 ‎May ‎2016 6:27:00 PM

**Comment by sallar** [comment]
We missed the certificate renewal notification. Renewed and working as expected now. Thank you for letting us know.
