### ISSUE TITLE
Retrieving username/password separately from the Credentials class using buttercup-core api 

### ISSUE THREAD

**Issue by srivignes** [buttercup-pw/buttercup#84]
I am trying to retrieve the username and password from an Entry so that I can use that to login to external systems. Here's is what I am trying to do.

    var Buttercup = require("buttercup");
    var archive = new Buttercup.Archive(),
    mainGroup = archive.createGroup("test-group-main"),
    mainEntry = mainGroup.createEntry("test-entry-main");
    var credentials=new Buttercup.Credentials(mainEntry);
    credentials.setIdentity("Michael","Password123");
    var model = new Buttercup.Model(credentials);
    model.set("bot-pass",credentials);
    console.log(model.getData()model._data.password);

Using this code, I am able to retrieve both username and password that I've entered. But is this the right way to do it? Don't we have getIdentity() under the Credentials class? Not more of an issue but couldn't find a discussion forum.

**Comment by srivignes** [comment]
@sallar : Hi, Could you help me with this issue ?

**Comment by perry-mitchell** [comment]
Hi @srivignes - I don't currently see any need, in your example, to use `Credentials`. You can simply get the username and password by `mainEntry.getProperty("username")` and `mainEntry.getProperty("password")`.

Credentials were designed to store intermediate login details for services such as webdav etc.

**Comment by srivignes** [comment]
@perry-mitchell - Thanks, Perry. I thought Credentials class is for securely retrieving and storing the username and password to the buttercup archive. I'll use Entry class then.

**Comment by perry-mitchell** [comment]
Unfortunately it's probably not so clear in the docs, I'll try to make a point of it.

Cheers
