### ISSUE TITLE
Encrypted content has been tampered with

### ISSUE THREAD

**Issue by aktary** [buttercup-pw/buttercup#87]
So, I've been able to get the UI to load (OS X, El Capitan), and even created a buttercup... but when I restart and try to open the buttercup, it prompts me for a password, doesn't accept it, and spits out "Failed opening archive: Error: Encrypted content has been tampered with" in the console log.  I haven't been able to find this message in the codebase, which suggests it's a package somewhere complaining about this.  Any ideas how to proceed?

Oh... eventually, if I keep trying the same or different passwords, the UI just closes without any message.

**Comment by aktary** [comment]
Ok... found the problem with the app closing for no apparent reason.  The password is successfully verified, then this bit (line 55 in events.js):

`// Close intro screen
           windowManager.getWindowsOfType("intro").forEach(function(window) {
                window.close();
            });`

closes the intro window, which is presumably the parent of the spawned window... which then closes the spawned workspace window... soo... that's gonna have to change.

**Comment by perry-mitchell** [comment]
Hi David,

Thanks for researching the issue. I don't think that the windows have parents, so closing one should not affect another. At least that's how I recall Electron functioning.

@sallar would be able to verify.

**Comment by sallar** [comment]
Hi @aktary, :)

Thanks for letting us know. Although @perry-mitchell is right, the windows should not be affected and the workspace window should not be of type "intro" thus should not be closed... I will try this on my machine more to see where’s the issue.

Also the error message you're referring to belongs to the "buttercup" core package which is used by the buttercup ui project.

Thanks!

**Comment by aktary** [comment]
@sallar cool... thanks.

On a separate note, I'd love to chat with you two if you have a minute.  We're strongly considering using Buttercup as the basis for one of our new projects and I'd like to run the idea by you to see if you see any major issues with doing so.  There may also be some consulting work in it for you, if you're interested.

**Comment by aktary** [comment]
Closing this issue, but would love to hear from you about whether or not you're available to consult a bit on this project, @sallar @perry-mitchell .

**Comment by perry-mitchell** [comment]
I'd love to speak more on this. Currently on leave with little access to Internet.. When I'm back I'll touch base with you. Apologies for the delay.

**Comment by aktary** [comment]
@perry-mitchell: feel free to email me when you get some time and internet access.  You can reach me at david@aktarytech.com.  In the meantime, enjoy your time off!

**Comment by perry-mitchell** [comment]
@aktary email sent.
