### ISSUE TITLE
Allow moving documents into other groups

### ISSUE THREAD

**Issue by CodeTheory** [buttercup-pw/buttercup#91]
Accidentally made documents in the wrong group, it'd be easier to move the document than remake it.

**Comment by perry-mitchell** [comment]
Great suggestions - Must haves from a usability perspective.

**Comment by sallar** [comment]
Thanks @CodeTheory, Buttercup UI is being re-engineered at the moment, and this is something that I’m actually working on right now. Full featured tree instead of just a normal representation of the folders.

**Comment by CodeTheory** [comment]
Awesome @sallar! I love the app, but I wanted to help make it more usable for people like me 😄 

Good work!

**Comment by sallar** [comment]
Closed by #92
