### ISSUE TITLE
Bug: Duplicate properties created when adding custom fields

### ISSUE THREAD

**Issue by RyanCwynar** [buttercup-pw/buttercup#97]
Attempts to add custom data to a property creates a new property with that field.

For instance, adding a domain name and a category to a property would result in 3 properties: the one with the initial data, the one with a domain name, and another with both a domain name and the category.

**Comment by perry-mitchell** [comment]
Were you still experiencing this @RyanCwynar? Did you do this through the interface?

**Comment by sallar** [comment]
@perry-mitchell Is this still valid? I can't replicate this.

**Comment by perry-mitchell** [comment]
Perhaps not.

Let us know if you notice it again @RyanCwynar and we can re-open.
